[build]
  publish = "build"
  command = "npm run build"
  functions = "functions"

[template.environment]
  NETLIFY_OAUTH_CLIENT_ID = "cIRL6QEl3anJ-SPsylnyfLhI-ZLUZjyUUHrhrb6yyzE"
  NETLIFY_OAUTH_CLIENT_SECRET= "qNHrP5Kp6NrR5fbUx23_w2tiH-GjuzbF2vEbIqdKHIo"
